server:
  port: 8086
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity-services"
    username: root
    password: 2901612
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "+9jcTqa2wQEddDWtn3KdCrIyalW7PKZ0G2Lx3T6QM2rk2LFHZ+6D5XnYeLYyZE6s"